name: atlas
output: atlas-results.txt
file: /Users/nick/mongodb/cloud-docs/config/htaccess.yaml
base: https://docs.atlas.mongodb.com/
---
name: compass
output: compass-results.txt
file: /Users/nick/mongodb/docs-compass/config/htaccess.yaml
base: https://docs.mongodb.com/compass/
---
name: stitch
output: stitch-results.txt
file: /Users/nick/mongodb/baas-docs/config/htaccess.yaml
base: https://docs.mongodb.com/stitch/
---
name: bi-connector
output: bi-connector-results.txt
file: /Users/nick/mongodb/docs-bi-connector/config/htaccess.yaml
base: https://docs.mongodb.com/bi-connector/
versions:
  - 2.2
  - 2.1
  - 2.0
  - 1.1
symlinks:
  - master -> 2.2
---
name: spark-connector
output: spark-results.txt
file: /Users/nick/mongodb/docs-spark-connector/config/htaccess.yaml
base: https://docs.mongodb.com/spark-connector/
versions:
  - 2.2
  - manual
  - 2.1
  - 2.0
  - 1.1
symlinks:
  - master -> 2.2
---
name: manual
output: manual-results.txt
file: /Users/nick/mongodb/docs/config/htaccess.yaml
base: https://docs.mongodb.com/
versions:
  - 3.6
  - 3.2
  - 3.0
  - 2.6
  - 2.4
  - 2.2
symlinks:
  - master -> 3.6
  - manual -> 3.4
---
name: ecosystem
output: ecosystem-results.txt
file: /Users/nick/mongodb/docs-ecosystem/config/htaccess.yaml
base: https://docs.mongodb.com/ecosystem/
---
# name: ruby-driver
# output: ruby-results.txt
# file: /Users/nick/mongodb/docs-ruby/config/htaccess.yaml
# base: https://docs.mongodb.com/ruby-driver/
# versions:
#   - 2.4
#   - 2.3
#   - 2.2
#   - 2.0
#   - 1.x
# symlinks:
#   - master -> 2.4
# ---
name: ops-manager
output: ops-manager-results.txt
file:
  - /Users/nick/mongodb/mms-docs/config/redirects-hosted.yaml
  - /Users/nick/mongodb/mms-docs/config/redirects-next-hosted.yaml
  - /Users/nick/mongodb/mms-docs/config/redirects-api.yaml
  - /Users/nick/mongodb/mms-docs/config/redirects-pdfs-onprem.yaml
base: https://docs.opsmanager.mongodb.com/
versions:
  - 3.4
  - 2.0
  - 1.8
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
  - 1.1
symlinks:
  - current -> 3.4
---
name: cloud-manager
output: cloud-manager-results.txt
file: /Users/nick/mongodb/mms-docs/config/redirects-cloud.yaml
base: https://docs.cloudmanager.mongodb.com/
