name: atlas
output: atlas-results.txt
file: /Users/nick/mongodb/cloud-docs/config/htaccess.yaml
base: https://docs.atlas.mongodb.com/
---
name: compass
output: compass-results.txt
file: /Users/nick/mongodb/docs-compass/config/htaccess.yaml
base: https://docs.mongodb.com/compass/
---
name: stitch
output: stitch-results.txt
file: /Users/nick/mongodb/baas-docs/config/htaccess.yaml
base: https://docs.mongodb.com/stitch/
---
name: bi-connector
output: bi-connector-results.txt
file: /Users/nick/mongodb/docs-bi-connector/config/htaccess.yaml
base: https://docs.mongodb.com/bi-connector/
versions:
  - 2.2
  - 2.1
  - 2.0
  - 1.1
symlinks:
  - master -> 2.2
---
name: spark-connector
output: spark-results.txt
file: /Users/nick/mongodb/docs-spark-connector/config/htaccess.yaml
base: https://docs.mongodb.com/spark-connector/
versions:
  - 2.2
  - manual
  - 2.1
  - 2.0
  - 1.1
symlinks:
  - master -> 2.2
---
name: manual
output: manual-results.txt
file: /Users/nick/mongodb/docs/config/htaccess.yaml
base: https://docs.mongodb.com/
versions:
  - 3.6
  - 3.2
  - 3.0
  - 2.6
  - 2.4
  - 2.2
symlinks:
  - master -> 3.6
  - manual -> 3.4
---
name: ecosystem
output: ecosystem-results.txt
file: /Users/nick/mongodb/docs-ecosystem/config/htaccess.yaml
base: https://docs.mongodb.com/ecosystem/
---
name: ruby-driver
output: ruby-results.txt
file: /Users/nick/mongodb/docs-ruby/config/htaccess.yaml
base: https://docs.mongodb.com/ruby-driver/
versions:
  - 2.4
  - 2.3
  - 2.2
  - 2.0
  - 1.x
symlinks:
  - master -> 2.4
