name: Allison

on:
  push:
    branches:
      - 'DOP-3557-releases'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: Setup poetry
      run: python3 -m pip install poetry
    - name: Install dependencies
      run: python3 -m poetry install
    - name: Build package
      id: build_package
      run: make package
    - name: Build wheel
      id: build_wheel
      run: make wheel
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          dist/${{ steps.build_package.outputs.package_filename }}
          dist/${{ steps.build_wheel.outputs.wheel_filename }}
