name: CI

on:
  push:
    branches:
    - main
    - 'v[0-9]*'
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04, macos-latest]
        python-version: ['3.8', '3.12']
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Setup poetry
      run: python3 -m pip install poetry
    - name: Install dependencies
      run: python3 -m poetry install
    - name: Lint
      run: make lint
    - name: Build package
      id: build_package
      run: make package
